### ISSUE TITLE
Timeout when calling into "parse" intent

### ISSUE THREAD

**Issue by patwhite** [kengz/aiva#30] opened 2016-11-11 23:35 UTC
I ran through the tutorial, and things work for simple commands (ping, for instance), but parsing is not working. When it's running, I see this failure:

>[Fri Nov 11 2016 23:32:36 GMT+0000 (UTC)] DEBUG IO on pass, msg: {
  "hash": "global-client-js_dd811cf6fe0efa148f76b0df27a5c37b",
  "from": "global-client-js",
  "input": "test",
  "to": "nlp.cgkb-py",
  "intent": "parse"
} fn: undefined

>Unhandled rejection TimeoutError: operation timed out
  at ontimeout (timers.js:365:14)
  at tryOnTimeout (timers.js:237:5)
  at Timer.listOnTimeout (timers.js:207:5)
From previous event:
  at cdefer (/Users/patwhite/Source/Temp/aiva2/node_modules/poly-socketio/src/global-client.js:93:6)
  at Socket.pass (/Users/patwhite/Source/Temp/aiva2/node_modules/poly-socketio/src/global-client.js:36:15)
  at Object.parse (/Users/patwhite/Source/Temp/aiva2/node_modules/spacy-nlp/src/nlp.js:16:24)
  at Object.<anonymous> (/Users/patwhite/Source/Temp/aiva2/node_modules/cgkb/src/cgkb.js:44:27)
  at undefined.next (native)
  at onFulfilled (/Users/patwhite/Source/Temp/aiva2/node_modules/co/index.js:65:19)
  at /Users/patwhite/Source/Temp/aiva2/node_modules/co/index.js:54:5
From previous event:
  at Object.co (/Users/patwhite/Source/Temp/aiva2/node_modules/co/index.js:50:10)
  at Object.createPromise [as add] (/Users/patwhite/Source/Temp/aiva2/node_modules/co/index.js:30:15)
  at TextListener.robot.respond [as callback] (/Users/patwhite/Source/Temp/aiva2/scripts/cgkb-demo.js:29:12)
  at /Users/patwhite/Source/Temp/aiva2/node_modules/hubot/src/listener.coffee:65:12
  at allDone (/Users/patwhite/Source/Temp/aiva2/node_modules/hubot/src/middleware.coffee:44:37)
  at /Users/patwhite/Source/Temp/aiva2/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/Users/patwhite/Source/Temp/aiva2/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/Users/patwhite/Source/Temp/aiva2/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /Users/patwhite/Source/Temp/aiva2/node_modules/hubot/src/middleware.coffee:49:13
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

I can use spacy separately for NLP, but maybe it's an issue with the socket io bridge?

I followed the tutorial directly, this is on Mac El Capitan, node 6.9.1, python 3.5.1.

**Comment by kengz** [comment] 2016-11-12 00:51
It's likely that the python client never joined. Can u compare your terminal log to #29 and see if you have all clients joining?

**Comment by kengz** [comment] 2017-01-08 15:22
cannot reproduce; attributing to client not joining: need to wait for the `All clients have joined` on stdout. closing.

**Closed by kengz** 2017-01-08 15:22 UTC
