### ISSUE TITLE
default reply for all inputs that doesnt have any modules/intent associated?

### ISSUE THREAD

**Issue by MayankTi** [kengz/aiva#5] opened 2016-05-12 17:27 UTC
Hi,

How do we return a default reply for all inputs that does not have a handling intent?
E.g. I pass "blah" as input. Their is no intent to handle this, hence I want to return a default reply to the user. 

Thanks & Regards

**Comment by kengz** [comment] 2016-05-12 22:11
Yo,

I suppose you're talking about the [polyglot `message` payload](http://kengz.me/aiva/#how-it-works-socket-io-logic-and-standard)?

By design the keys `to` and `intent` need to be valid, since you'd send such a payload if only you have a target, for example in the case of translation. `to` specifies the script name, e.g. `ai.py`, and `intent` the function you wish to call, e.g. `nlp.translate`. You cannot dynamically specify these 2 keys since you cannot create functions on the fly. Nor shall user input be used for specifying what functions to call, for safety (imagine deleting files from system if one exposes critical functions by mistake.)

That being said, the functions you define are like bouncing boards on the sea. You should aim your `msg` at them; those that miss will drop into the sea, never to be heard of again (until your `global.gPass`'s promise expires and it warns you).

However you can still do a reply: use the promise just mentioned:

```javascript
global.gPass({
  input: "hola amigos",
  to: 'ai.py',
  intent: 'nlp.translate'
})
.then(res.reply) // normal function execution
.catch(function(err) {
  console.log(err)
  res.reply("lost in the sea") // when it misses
})
```

I might be misunderstanding your question here. But do let me know :)

**Comment by MayankTi** [comment] 2016-05-13 14:02
Thanks a lot for your reply, it seems to have answered my question. I will use the capture everything regex and then route the input to the relevant handler. Though this will be costly on the processing side, but it will give more flexibility and a better experience to the user (i presume). 

Thanks :)

**Comment by kengz** [comment] 2016-05-13 14:07
yep. the hubot base is designed to capture a limited set of inputs. [More here](https://github.com/github/hubot/blob/master/docs/scripting.md).

Capturing all inputs in fact isn't more costly, since hubot is already matching every input. Now it's just doing a lazy `/.+/` match - there isn't more operation here. Processing the captured inputs tho - a lazy echo for irrelevant input; handler for the relevant ones. So nothing to really worry here :)

In fact I was trying to use a RNN to do the input delegation. Recently new developments such as [wit.ai bot engine](https://wit.ai) and [viv.ai](http://viv.ai) provide pretty good alternatives.

Closing this. Let me know if you have more questions!

**Closed by kengz** 2016-05-13 14:07 UTC
